/**
 * Abstract syntax tree (AST) node definitions for JsonValue.
 * <p>
 * Auto-generated by tool/GenerateAst.java. Do NOT edit manually.
 * </p>
 */
package io.github.journeycodesayush.javajson.parser;

import java.util.Map;
import java.util.List;

public sealed interface JsonValue {

    <R> R accept(Visitor<R> visitor);

    /**
     * Visitor interface for JsonValue nodes.
     * Each concrete node implements the accept() method.
     */
    public interface Visitor<R> {
        R visitJsonObject(JsonObject jsonvalue);

        R visitJsonArray(JsonArray jsonvalue);

        R visitJsonString(JsonString jsonvalue);

        R visitJsonNumber(JsonNumber jsonvalue);

        R visitJsonBoolean(JsonBoolean jsonvalue);

        R visitJsonNull(JsonNull jsonvalue);
    }

    public record JsonObject(Map<String, JsonValue> members) implements JsonValue {

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitJsonObject(this);
        }
    }

    public record JsonArray(List<JsonValue> elements) implements JsonValue {

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitJsonArray(this);
        }
    }

    public record JsonString(String value) implements JsonValue {

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitJsonString(this);
        }
    }

    public record JsonNumber(double value) implements JsonValue {

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitJsonNumber(this);
        }
    }

    public record JsonBoolean(boolean value) implements JsonValue {

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitJsonBoolean(this);
        }
    }

    public record JsonNull() implements JsonValue {

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitJsonNull(this);
        }
    }
}
