package io.github.journeycodesayush.javajson.tool;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.List;

/**
 * Utility tool to automatically generate abstract syntax tree (AST) classes for a JSON parser.
 *
 * <p>Generates Java source files for a sealed interface (JsonValue) and its derived record types,
 * each implementing the visitor pattern.
 *
 * <p>This class is intended to be run from the command line with a single argument specifying the
 * output directory for the generated files.
 */
public class GenerateAst {

  /**
   * Entry point for the AST generation tool.
   *
   * @param args command-line arguments; args[0] must be the output directory
   * @throws IOException if writing to a file fails
   */
  public static void main(String[] args) throws IOException {
    if (args.length != 1) {
      System.err.println("Usage generate_ast <output directory>");
      System.exit(64);
    }
    String outputDir = args[0];
    defineAst(
        outputDir,
        "JsonValue",
        Arrays.asList(
            "JsonObject : Map<String, JsonValue> members",
            "JsonArray : List<JsonValue> elements",
            "JsonString : String value",
            "JsonNumber : double value",
            "JsonBoolean : boolean value",
            "JsonNull : "));
  }

  /**
   * Generates a Java source file containing a sealed interface and its nested record types for the
   * given base name and type definitions.
   *
   * @param outputDir the directory where the generated file will be saved
   * @param baseName the name of the base interface (e.g., "JsonValue")
   * @param types a list of type definitions in the format "ClassName : fields"
   * @throws IOException if writing to the file fails
   */
  private static void defineAst(String outputDir, String baseName, List<String> types)
      throws IOException {
    String path = outputDir + "/" + baseName + ".java";
    PrintWriter writer = new PrintWriter(path, "UTF-8");

    writer.println("/**");
    writer.println(" * Abstract syntax tree (AST) node definitions for " + baseName + ".");
    writer.println(" * <p>");
    writer.println(" * Auto-generated by tool/GenerateAst.java. Do NOT edit manually.");
    writer.println(" * </p>");
    writer.println(" */");

    writer.println("package io.github.journeycodesayush.javajson.parser;");
    writer.println();
    writer.println("import java.util.Map;");
    writer.println("import java.util.List;");
    writer.println();
    // writer.println("public sealed interface " + baseName + " {");
    writer.println("public sealed interface " + baseName + " {");
    writer.println();

    writer.println("    <R> R accept(Visitor<R> visitor);");
    writer.println();

    defineVisitor(writer, baseName, types);

    writer.println();

    for (String type : types) {
      String className = type.split(":")[0].trim();
      String fields = type.split(":")[1].trim();
      defineType(writer, baseName, className, fields);
    }

    writer.println("}");
    writer.close();
  }

  /**
   * Writes a record type implementing the base interface to the output file.
   *
   * @param writer the {@link PrintWriter} to write to
   * @param baseName the base interface name
   * @param className the record class name
   * @param fieldList the comma-separated field declarations
   */
  private static void defineType(
      PrintWriter writer, String baseName, String className, String fieldList) {
    writer.println(
        "    public record " + className + "(" + fieldList + ") implements " + baseName + " {");

    writer.println();
    writer.println("        @Override");
    writer.println("        public <R> R accept(Visitor<R> visitor) {");
    writer.println("            return visitor.visit" + className + "(this);");
    writer.println("        }");

    writer.println("    }");
  }

  /**
   * Writes the Visitor interface for the given base interface and types.
   *
   * @param writer the {@link PrintWriter} to write to
   * @param baseName the base interface name
   * @param types the list of type definitions
   */
  private static void defineVisitor(PrintWriter writer, String baseName, List<String> types) {
    writer.println("    /**");
    writer.println("     * Visitor interface for " + baseName + " nodes.");
    writer.println("     * Each concrete node implements the accept() method.");
    writer.println("     */");
    writer.println("    public interface Visitor<R> {");
    for (String type : types) {
      String typeName = type.split(":")[0].trim();
      writer.println(
          "        R visit" + typeName + "(" + typeName + " " + baseName.toLowerCase() + ");");
    }
    writer.println("    }");
  }
}
